import { StyleSheet, Dimensions } from 'react-native';
import Constants from 'expo-constants';
import { colors } from './globalStyles/colors';

export const { width: windowWidth } = Dimensions.get('window');
const statusBarHeight = Constants.statusBarHeight;

export const spaceDetailsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
    marginTop: statusBarHeight,
  },
  statusBarGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: statusBarHeight + 0,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  imageContainer: {
    height: 300,
    position: 'relative',
  },
  image: {
    width: windowWidth,
    height: 300,
  },
  backButtonFixed: {
    position: 'absolute',
    top: 16,
    left: 16,
    zIndex: 100,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 20,
    padding: 8,
  },
  dotsContainer: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 3,
  },
  dotActive: {
    backgroundColor: colors.white,
  },
  dotInactive: {
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  counter: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  counterText: {
    color: colors.white,
    fontSize: 12,
  },
  content: {
    marginHorizontal: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 8,
  },
  address: {
    fontSize: 16,
    color: colors.gray,
    marginBottom: 16,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  rating: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.black,
    marginLeft: 4,
  },
  reviews: {
    fontSize: 14,
    color: colors.gray,
    marginLeft: 4,
  },
  price: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.blue,
    marginBottom: 24,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 12,
  },
  description: {
    fontSize: 16,
    color: colors.gray,
    lineHeight: 24,
  },
  moreButton: {
    marginTop: 8,
  },
  moreButtonText: {
    fontSize: 14,
    color: colors.blue,
    fontWeight: 'bold',
  },
  amenityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  amenityText: {
    fontSize: 16,
    color: colors.gray,
    marginLeft: 8,
  },
  bookingCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  column: {
    flex: 1,
    alignItems: 'flex-start',
  },
  verticalDivider: {
    width: 1,
    backgroundColor: colors.light_gray,
    marginHorizontal: 12,
  },
  horizontalDivider: {
    height: 1,
    backgroundColor: colors.line,
    marginVertical: 24,
    marginHorizontal: -6,
  },
  label: {
    fontWeight: 'bold',
    color: colors.gray,
    marginBottom: 4,
    fontSize: 15,
  },
  valueBox: {
    backgroundColor: colors.white,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  valueText: {
    fontSize: 18,
    color: colors.black,
    fontWeight: 'bold',
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.black,
    marginTop: 2,
  },
  rentButton: {
    backgroundColor: colors.blue,
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  rentButtonText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: 'bold',
  },
  calendarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarModal: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    width: '85%',
  },
  timeList: {
    padding: 8,
  },
  timeItem: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 12,
    margin: 4,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  timeText: {
    fontSize: 16,
    color: colors.black,
  },
  confirmModal: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: 280,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  confirmText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    marginTop: 16,
    textAlign: 'center',
  },
  reviewCard: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.line,
    boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.2)',
    width: 300,
  },
  reviewUser: {
    fontWeight: 'bold',
    fontSize: 16,
    color: colors.black,
    marginBottom: 4,
  },
  reviewRating: {
    color: colors.gray,
    fontSize: 12,
    marginBottom: 8,
  },
  reviewText: {
    fontSize: 14,
    color: colors.gray,
    lineHeight: 20,
  },
  reviewMoreButton: {
    color: colors.blue,
    fontWeight: 'bold',
    marginTop: 8,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  headerInfo: {
    flex: 1,
  },
  headerRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  headerAddress: {
    color: colors.blue,
    textDecorationLine: 'underline',
    fontSize: 16,
  },
  headerReviews: {
    marginLeft: 4,
    color: colors.gray,
    fontSize: 16,
  },
  detailsRow: {
    flexDirection: 'row',
  },
  detailsValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  detailsColLeft: {
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    paddingRight: 16,
  },
  detailsColRight: {
    flex: 2,
    paddingLeft: 16,
  },
  detailsLabel: {
    color: colors.gray,
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 4,
  },
  detailsValue: {
    fontWeight: 'bold',
    fontSize: 20,
    color: colors.blue,
  },
  detailsDivider: {
    color: colors.gray,
    fontSize: 14,
    marginBottom: 2,
    marginLeft: 2,
  },
  detailsType: {
    fontWeight: 'bold',
    fontSize: 17,
    color: colors.black,
  },
  detailsIcon: {
    marginRight: 6,
  },
  detailsMoreButton: {
    textAlign: 'center',
    color: colors.blue,
    fontSize: 14,
  },
  detailsInnerDivider: {
    height: 1,
    backgroundColor: colors.line,
    marginVertical: 8,
  },
  detailsInfoText: {
    fontSize: 16,
    color: colors.black,
    marginRight: 16,
  },
  detailsInfoTextNoMargin: {
    fontSize: 16,
    color: colors.black,
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  detailsGridItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  rentalSection: {
    alignItems: 'center',
    marginTop: 22,
    marginBottom: 34,
  },
  rentalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  rentalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.black,
    marginLeft: 8,
  },
  rentalSubtitle: {
    fontSize: 16,
    color: colors.gray,
    textAlign: 'center',
    marginBottom: 24,
  },
  rentalCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 24,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  rentalDateTimeContainer: {
    marginBottom: 20,
  },
  rentalDateTimeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  rentalIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.others[100],
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rentalDateTimeTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
  },
  rentalDateTimeContent: {
    flexDirection: 'row',
    gap: 16,
  },
  rentalDateTimeBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderRadius: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 10,
    boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.15)',
  },
  rentalDateTimeIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.light_gray,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rentalDateTimeTextContainer: {
    flex: 1,
  },
  rentalDateTimeLabel: {
    fontSize: 12,
    color: colors.gray,
    marginBottom: 2,
  },
  rentalDateTimeText: {
    fontSize: 16,
    color: colors.black,
    fontWeight: '500',
  },
  rentalDivider: {
    height: 1,
    backgroundColor: colors.line,
    marginVertical: 20,
  },
  rentalTotalContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  rentalTotalInfo: {
    flex: 1,
  },
  rentalTotalLabel: {
    fontSize: 14,
    color: colors.gray,
    marginBottom: 4,
  },
  rentalTotalValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.black,
  },
  rentalButton: {
    backgroundColor: colors.blue,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  rentalButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  reviewBox: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
  },
  reviewBoxHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  reviewBoxTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.black,
  },
  clearButton: {
    padding: 8,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
  },
  reviewStarsRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  reviewInput: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    padding: 12,
    minHeight: 70,
    fontSize: 15,
    marginBottom: 16,
    backgroundColor: colors.white,
    textAlignVertical: 'top',
  },
  reviewButton: {
    backgroundColor: colors.blue,
    borderRadius: 6,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  successModal: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: 280,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  successText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    marginTop: 16,
    textAlign: 'center',
  },
  detailsModal: {
    backgroundColor: colors.white,
    borderRadius: 16,
    width: '90%',
    height: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    overflow: 'hidden',
  },
  detailsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    backgroundColor: colors.white,
  },
  detailsModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.black,
  },
  detailsModalCloseButton: {
    padding: 4,
  },
  detailsModalScrollView: {
    flex: 1,
  },
  detailsModalContent: {
    padding: 16,
  },
  detailsModalImageContainer: {
    height: 200,
    position: 'relative',
    alignItems: 'center',
    marginTop: 16,
  },
  detailsModalImage: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 4,
    borderColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  detailsModalImageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    padding: 16,
  },
  detailsModalImageTitle: {
    color: colors.black,
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 16,
    textAlign: 'center',
  },
  detailsModalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 24,
  },
  detailsModalGridItem: {
    width: '45%',
    alignItems: 'center',
    padding: 12,
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  detailsModalIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.light_gray,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  detailsModalGridLabel: {
    fontSize: 14,
    color: colors.gray,
    marginBottom: 4,
  },
  detailsModalGridValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.black,
  },
  detailsModalAmenities: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  detailsModalSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 12,
  },
  detailsModalAmenitiesList: {
    gap: 8,
  },
  detailsModalAmenityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.line,
  },
  detailsModalAmenityText: {
    fontSize: 16,
    color: colors.black,
  },
}); 