import { StyleSheet, Dimensions } from 'react-native';
import Constants from 'expo-constants';
import { colors } from './globalStyles/colors';

export const { width: windowWidth } = Dimensions.get('window');
const statusBarHeight = Constants.statusBarHeight;

export const spaceDetailsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
    marginTop: statusBarHeight,
  },
  statusBarGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: statusBarHeight + 0,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  imageContainer: {
    height: 300,
    position: 'relative',
  },
  image: {
    width: windowWidth,
    height: 300,
  },
  backButtonFixed: {
    position: 'absolute',
    top: 16,
    left: 16,
    zIndex: 100,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 20,
    padding: 8,
  },
  dotsContainer: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 3,
  },
  dotActive: {
    backgroundColor: colors.white,
  },
  dotInactive: {
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  counter: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  counterText: {
    color: colors.white,
    fontSize: 12,
  },
  content: {
    marginHorizontal: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 8,
  },
  address: {
    fontSize: 16,
    color: colors.gray,
    marginBottom: 16,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  rating: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.black,
    marginLeft: 4,
  },
  reviews: {
    fontSize: 14,
    color: colors.gray,
    marginLeft: 4,
  },
  price: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.blue,
    marginBottom: 24,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 12,
  },
  description: {
    fontSize: 16,
    color: colors.gray,
    lineHeight: 24,
  },
  moreButton: {
    marginTop: 8,
  },
  moreButtonText: {
    fontSize: 14,
    color: colors.blue,
    fontWeight: 'bold',
  },
  amenityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  amenityText: {
    fontSize: 16,
    color: colors.gray,
    marginLeft: 8,
  },
  bookingCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  column: {
    flex: 1,
    alignItems: 'flex-start',
  },
  verticalDivider: {
    width: 1,
    backgroundColor: colors.light_gray,
    marginHorizontal: 12,
  },
  horizontalDivider: {
    height: 1,
    backgroundColor: colors.line,
    marginVertical: 32,
    marginHorizontal: -6,
  },
  label: {
    fontWeight: 'bold',
    color: colors.gray,
    marginBottom: 4,
    fontSize: 15,
  },
  valueBox: {
    backgroundColor: colors.white,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  valueText: {
    fontSize: 18,
    color: colors.black,
    fontWeight: 'bold',
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.black,
    marginTop: 2,
  },
  rentButton: {
    backgroundColor: colors.blue,
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  rentButtonText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: 'bold',
  },
  calendarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarModal: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    width: '85%',
  },
  timeList: {
    padding: 8,
  },
  timeItem: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 12,
    margin: 4,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  timeText: {
    fontSize: 16,
    color: colors.black,
  },
  confirmModal: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: 280,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  confirmText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.black,
    marginTop: 16,
    textAlign: 'center',
  },
  reviewCard: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  reviewUser: {
    fontWeight: 'bold',
    fontSize: 16,
    color: colors.black,
    marginBottom: 4,
  },
  reviewRating: {
    color: colors.gray,
    fontSize: 12,
    marginBottom: 8,
  },
  reviewText: {
    fontSize: 14,
    color: colors.gray,
    lineHeight: 20,
  },
  reviewMoreButton: {
    color: colors.blue,
    fontWeight: 'bold',
    marginTop: 8,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  headerInfo: {
    flex: 1,
  },
  headerRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  headerAddress: {
    color: colors.blue,
    textDecorationLine: 'underline',
    fontSize: 16,
  },
  headerReviews: {
    marginLeft: 4,
    color: colors.gray,
    fontSize: 16,
  },
  detailsRow: {
    flexDirection: 'row',
  },
  detailsValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  detailsColLeft: {
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    paddingRight: 16,
  },
  detailsColRight: {
    flex: 2,
    paddingLeft: 16,
  },
  detailsLabel: {
    color: colors.gray,
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 4,
  },
  detailsValue: {
    fontWeight: 'bold',
    fontSize: 20,
    color: colors.blue,
  },
  detailsDivider: {
    color: colors.gray,
    fontSize: 14,
    marginBottom: 2,
    marginLeft: 2,
  },
  detailsType: {
    fontWeight: 'bold',
    fontSize: 17,
    color: colors.black,
  },
  detailsIcon: {
    marginRight: 6,
  },
  detailsMoreButton: {
    textAlign: 'center',
    color: colors.blue,
    fontSize: 14,
  },
  detailsInnerDivider: {
    height: 1,
    backgroundColor: colors.line,
    marginVertical: 8,
  },
  detailsInfoText: {
    fontSize: 16,
    color: colors.black,
    marginRight: 16,
  },
  detailsInfoTextNoMargin: {
    fontSize: 16,
    color: colors.black,
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  detailsGridItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  rentalSection: {
    alignItems: 'center',
    marginBottom: 32,
  },
  rentalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
    color: colors.black,
  },
  rentalSubtitle: {
    fontSize: 14,
    color: colors.gray,
    textAlign: 'center',
    marginBottom: 16,
  },
  rentalCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    width: '100%',
    maxWidth: 340,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.line,
  },
  rentalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  rentalColumn: {
    flex: 1,
    alignItems: 'flex-start',
  },
  rentalLabel: {
    fontSize: 14,
    color: colors.gray,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  rentalValueBox: {
    backgroundColor: colors.white,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.line,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  rentalValueText: {
    fontSize: 16,
    color: colors.black,
    fontWeight: 'bold',
  },
  rentalVerticalDivider: {
    width: 1,
    backgroundColor: colors.line,
    marginHorizontal: 16,
  },
  rentalHorizontalDivider: {
    height: 1,
    backgroundColor: colors.line,
    marginVertical: 12,
  },
  rentalTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rentalTotalValue: {
    fontSize: 20,
    color: colors.black,
    fontWeight: 'bold',
  },
  rentalButton: {
    backgroundColor: colors.blue,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 2,
  },
  rentalButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
}); 