import { StyleSheet } from 'react-native';
import { colors } from '../globalStyles/colors';
import Constants from 'expo-constants';

const statusBarHeight = Constants.statusBarHeight;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.light_gray,
    marginTop: Constants.statusBarHeight,
  },
  progressContainer: {
    backgroundColor: colors.white,
    paddingTop: 20,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: colors.light_gray,
    marginBottom: 16,
  },
  formContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 8,
    marginTop: 16,
    paddingHorizontal: 4,
  },
  subtitle: {
    fontSize: 16,
    color: colors.dark_gray,
    lineHeight: 22,
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  sectionContainer: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: colors.black,
    marginBottom: 8,
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 16,
    color: colors.dark_gray,
    marginBottom: 8,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.gray,
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 16,
    color: colors.dark_gray,
  },
  textArea: {
    borderWidth: 1,
    borderColor: colors.light_gray,
    borderRadius: 6,
    padding: 12,
    fontSize: 16,
    color: colors.black,
    height: 120,
    textAlignVertical: 'top',
  },
  documentContainer: {
    marginBottom: 24,
  },
  documentTitle: {
    fontSize: 16,
    color: colors.dark_gray,
    marginBottom: 8,
  },
  documentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.blue,
    borderRadius: 6,
    padding: 12,
    gap: 8,
  },
  documentButtonText: {
    fontSize: 16,
    color: colors.blue,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.blue,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.blue,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: 16,
    color: colors.black,
  },
  checkboxDescription: {
    fontSize: 14,
    color: colors.gray,
    marginTop: 4,
    marginLeft: 36,
  },
  documentPreview: {
    marginVertical: 12,
    alignItems: 'flex-start',
  },
  previewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.light_blue,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  previewText: {
    color: colors.blue,
    fontSize: 16,
    marginLeft: 8,
    fontWeight: '600',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    maxWidth: '90%',
    maxHeight: '80%',
  },
  closeButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 2,
  },
  modalImage: {
    width: 300,
    height: 400,
    resizeMode: 'contain',
    marginTop: 32,
  },
  buttonRowFixed: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.light_gray,
    gap: 12,
  },
  navigationButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 4,
    backgroundColor: colors.blue,
  },
  navigationButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  selectButton: {
    flex: 1,
    height: 48,
    backgroundColor: colors.blue,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  removeButton: {
    flex: 1,
    height: 48,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.blue,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeButtonText: {
    color: colors.blue,
    fontSize: 16,
    fontWeight: '600',
  },
  errorText: {
    color: colors.error,
    fontSize: 14,
    marginTop: 4,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 24,
  },
  disabled: {
    opacity: 0.5,
  },
}); 